
export interface Lesson {
  id: string;
  title: string;
  content: string;
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  answer: number; // index of correct option
}

export interface EduModule {
  id: string;
  title: string;
  badge: string;
  lessons: Lesson[];
  quiz: QuizQuestion[];
}

export const modules: EduModule[] = [
  {
    id: "bivak",
    title: "Membuat Bivak",
    badge: "Bivak Builder",
    lessons: [
      { id: "bivak-1", title: "Pengantar Bivak", content: "Bivak adalah tempat perlindungan darurat yang dibangun di alam terbuka untuk melindungi diri dari cuaca buruk, hewan liar, dan bahaya lingkungan lainnya. Dalam Mahapala Narotama, pembuatan bivak menjadi latihan wajib yang mengajarkan anggota untuk berpikir kreatif, memanfaatkan sumber daya alam, dan bekerja sama dalam tim. Pembuatan bivak juga melatih kemampuan adaptasi, pengambilan keputusan cepat, dan kesiapsiagaan menghadapi situasi darurat. Setiap anggota diajak untuk memahami pentingnya perlindungan diri, baik secara fisik maupun mental, selama berada di alam bebas." },
      { id: "bivak-2", title: "Pemilihan Lokasi dan Perencanaan Bivak", content: "Memilih lokasi bivak tidak boleh sembarangan. Lokasi ideal adalah datar, tidak berada di bawah pohon rapuh, jauh dari jalur air, dan terlindung dari angin kencang. Selain itu, perhatikan juga kemungkinan bahaya seperti longsor, serangan hewan, atau banjir. Perencanaan meliputi penentuan arah pintu bivak, akses keluar-masuk, serta pemanfaatan bahan alami di sekitar. Anggota Mahapala Narotama diajarkan untuk selalu melakukan observasi lingkungan sebelum membangun bivak, serta berdiskusi dengan tim untuk menentukan lokasi terbaik." },
      { id: "bivak-3", title: "Teknik dan Bahan Membangun Bivak", content: "Bivak dapat dibuat dari berbagai bahan, seperti ponco, terpal, plastik, atau bahan alami seperti daun besar, ranting, dan bambu. Teknik membangun meliputi pemasangan tali simpul, pembuatan rangka, dan penutup yang rapat agar tahan angin dan hujan. Penting untuk memastikan struktur bivak kokoh, tidak mudah roboh, dan cukup luas untuk seluruh anggota tim. Dalam pelatihan Mahapala Narotama, anggota juga diajarkan teknik improvisasi jika perlengkapan terbatas, serta pentingnya menjaga kebersihan dan kelestarian lingkungan sekitar bivak." },
      { id: "bivak-4", title: "Pengalaman, Nilai, dan Evaluasi Bivak", content: "Pembuatan bivak bukan hanya soal teknis, tapi juga menanamkan nilai gotong royong, kepedulian, dan solidaritas antaranggota Mahapala Narotama. Setiap pengalaman membangun bivak menjadi pelajaran berharga tentang pentingnya komunikasi, pembagian tugas, dan saling membantu. Setelah bivak selesai, lakukan evaluasi: cek kekuatan struktur, kenyamanan, dan keamanan. Diskusikan apa yang bisa diperbaiki untuk kegiatan berikutnya. Dengan demikian, setiap anggota tidak hanya mahir secara teknis, tetapi juga tumbuh dalam karakter dan kepedulian sosial." }
    ],
    quiz: [
      { id: "bivak-q1", question: "Apa alasan utama memilih lokasi bivak yang datar dan jauh dari jalur air?", options: ["Agar bivak tidak mudah tergenang air saat hujan deras", "Agar mudah mengambil air minum", "Agar dekat dengan sumber makanan", "Agar lebih mudah membangun api unggun"], answer: 0 },
      { id: "bivak-q2", question: "Dari pilihan berikut, mana yang PALING TEPAT untuk bahan penutup bivak darurat di hutan tropis?", options: ["Daun lebar dan ponco", "Ranting kecil saja", "Tanah dan batu", "Tali rafia dan plastik tipis"], answer: 0 },
      { id: "bivak-q3", question: "Jika hanya membawa ponco dan tali, apa langkah pertama membangun bivak saat hujan mulai turun?", options: ["Cari lokasi aman, pasang ponco sebagai atap, lalu perkuat dengan tali", "Langsung pasang ponco di tanah tanpa tali", "Buat api dulu baru pasang ponco", "Tunggu hujan reda lalu membangun bivak"], answer: 0 },
      { id: "bivak-q4", question: "Apa risiko utama membangun bivak di bawah pohon besar yang sudah tua?", options: ["Ranting atau pohon bisa tumbang saat angin kencang", "Lebih mudah mencari kayu bakar", "Lebih teduh dan sejuk", "Lebih dekat dengan sumber air"], answer: 0 },
      { id: "bivak-q5", question: "Dari pilihan berikut, mana yang PALING BENAR tentang evaluasi bivak setelah selesai dibangun?", options: ["Cek kekuatan, kenyamanan, dan keamanan bivak bersama tim", "Langsung tidur tanpa cek", "Tinggalkan bivak untuk tim lain", "Bongkar bivak setelah selesai"], answer: 0 },
      { id: "bivak-q6", question: "Jika anggota tim ada yang tidak bisa membuat simpul tali, apa yang sebaiknya dilakukan?", options: ["Ajari dan praktik bersama sampai bisa", "Biarkan saja, yang penting jadi", "Suruh anggota lain saja yang mengikat", "Tunda pembuatan bivak"], answer: 0 },
      { id: "bivak-q7", question: "Apa manfaat utama membangun bivak bersama tim?", options: ["Pekerjaan lebih cepat selesai dan solidaritas meningkat", "Lebih banyak diskusi", "Lebih banyak bahan terpakai", "Lebih banyak waktu istirahat"], answer: 0 },
      { id: "bivak-q8", question: "Jika hanya tersedia daun kecil dan ranting, apa solusi terbaik untuk membuat bivak tahan hujan?", options: ["Susun daun dan ranting rapat-rapat sebagai atap", "Gunakan ranting saja tanpa daun", "Buat atap dari tanah", "Tunggu sampai ada bahan lain"], answer: 0 },
      { id: "bivak-q9", question: "Apa yang PALING PENTING dilakukan sebelum meninggalkan lokasi bivak?", options: ["Pastikan tidak ada sampah dan lingkungan tetap bersih", "Tinggalkan saja karena sudah selesai", "Bakar semua sisa bahan", "Tinggalkan alat di lokasi"], answer: 0 },
      { id: "bivak-q10", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai pembuatan bivak di Mahapala Narotama?", options: ["Menanamkan gotong royong, kepedulian, dan evaluasi diri", "Hanya soal teknik membangun", "Hanya soal kecepatan kerja", "Hanya soal perlombaan antar tim"], answer: 0 }
    ]
  },
  // 19 modul tambahan
  { id: "ppgd", title: "Pertolongan Pertama Gawat Darurat", badge: "PPGD Hero", lessons: [
    { id: "ppgd-1", title: "Pengantar PPGD", content: "Pertolongan Pertama Gawat Darurat (PPGD) adalah serangkaian tindakan awal yang diberikan kepada korban kecelakaan atau sakit mendadak sebelum mendapatkan pertolongan medis lanjutan. Dalam Mahapala Narotama, PPGD menjadi materi wajib karena kegiatan di alam terbuka memiliki risiko tinggi cedera, luka, atau kecelakaan. Anggota dilatih untuk tetap tenang, sigap, dan mampu mengambil keputusan cepat dalam situasi darurat. PPGD tidak hanya soal teknik, tetapi juga soal empati, komunikasi, dan kerja sama tim dalam menyelamatkan nyawa." },
    { id: "ppgd-2", title: "Penilaian dan Penanganan Korban", content: "Langkah pertama PPGD adalah menilai kondisi korban: cek kesadaran, pernapasan, denyut nadi, dan adanya perdarahan. Prioritaskan penanganan pada masalah yang mengancam nyawa, seperti henti napas, perdarahan hebat, atau syok. Penanganan awal meliputi pembukaan jalan napas, bantuan napas buatan, penekanan luka, dan pembidaian patah tulang. Anggota Mahapala Narotama diajarkan untuk selalu mengutamakan keselamatan diri dan korban, serta meminta bantuan jika situasi tidak terkendali." },
    { id: "ppgd-3", title: "Teknik CPR, Luka, dan Patah Tulang", content: "Teknik CPR (Cardiopulmonary Resuscitation) digunakan pada korban henti napas dan jantung. Langkahnya: cek respons, panggil bantuan, lakukan kompresi dada dan bantuan napas. Penanganan luka meliputi pembersihan, penekanan, dan pembalutan. Untuk patah tulang, lakukan pembidaian dengan alat yang ada, pastikan tidak ada pergerakan pada bagian yang patah. Semua tindakan harus dilakukan dengan hati-hati, memperhatikan kenyamanan dan keselamatan korban." },
    { id: "ppgd-4", title: "Evaluasi, Komunikasi, dan Nilai PPGD", content: "Setelah tindakan PPGD, lakukan evaluasi kondisi korban secara berkala. Komunikasikan kondisi korban ke tim dan petugas medis. Nilai utama PPGD di Mahapala Narotama adalah kepedulian, ketenangan, dan kerja sama. Setiap latihan PPGD bertujuan membentuk anggota yang sigap, empati, dan mampu bertindak efektif dalam situasi darurat di alam bebas." }
    ],
    quiz: [
      { id: "ppgd-q1", question: "Apa langkah PALING PERTAMA yang harus dilakukan saat menemukan korban tidak sadarkan diri di hutan?", options: ["Pastikan keamanan lokasi, lalu cek respons korban", "Langsung lakukan CPR tanpa cek", "Pindahkan korban ke tempat lain", "Berikan minum segera"], answer: 0 },
      { id: "ppgd-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang urutan penanganan korban patah tulang?", options: ["Stabilkan bagian yang patah, lakukan pembidaian, dan pantau kondisi korban", "Angkat korban ke tempat aman tanpa pembidaian", "Beri makan lalu bawa ke rumah sakit", "Tunggu sampai korban bisa berjalan sendiri"], answer: 0 },
      { id: "ppgd-q3", question: "Jika korban mengalami perdarahan hebat pada kaki, apa tindakan PALING TEPAT?", options: ["Tekan luka dengan perban bersih dan angkat kaki lebih tinggi dari jantung", "Beri air minum sebanyak-banyaknya", "Tunggu darah berhenti sendiri", "Bungkus kaki dengan plastik"], answer: 0 },
      { id: "ppgd-q4", question: "Apa tujuan utama melakukan CPR pada korban henti napas dan jantung?", options: ["Mengembalikan sirkulasi oksigen ke otak dan organ vital", "Membuat korban sadar secepatnya", "Mengurangi rasa sakit korban", "Menghentikan perdarahan"], answer: 0 },
      { id: "ppgd-q5", question: "Jika korban sadar setelah PPGD, apa langkah berikutnya?", options: ["Pantau kondisi korban dan siapkan evakuasi ke medis", "Tinggalkan korban karena sudah sadar", "Beri makan dan minum sebanyak-banyaknya", "Langsung angkat korban tanpa cek ulang"], answer: 0 },
      { id: "ppgd-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang komunikasi dalam PPGD?", options: ["Sampaikan kondisi korban secara jelas ke tim dan petugas medis", "Hanya tim yang tahu kondisi korban", "Tidak perlu komunikasi jika korban sadar", "Tunda komunikasi sampai evakuasi selesai"], answer: 0 },
      { id: "ppgd-q7", question: "Jika korban tidak bernapas, apa urutan tindakan yang PALING BENAR?", options: ["Buka jalan napas, cek pernapasan, lakukan bantuan napas buatan", "Langsung lakukan CPR tanpa cek", "Beri minum dulu baru CPR", "Pindahkan korban sebelum tindakan"], answer: 0 },
      { id: "ppgd-q8", question: "Apa yang PALING PENTING dilakukan setelah tindakan PPGD selesai?", options: ["Evaluasi kondisi korban secara berkala dan siapkan evakuasi", "Langsung tinggalkan korban", "Beri makan sebanyak-banyaknya", "Bungkus korban dengan selimut saja"], answer: 0 },
      { id: "ppgd-q9", question: "Jika korban mengalami syok, apa tindakan PALING TEPAT?", options: ["Baringkan korban, jaga kehangatan, dan pantau kondisi vital", "Beri minum manis sebanyak-banyaknya", "Angkat kaki korban lebih tinggi dari kepala saja", "Tunggu sampai korban sadar sendiri"], answer: 0 },
      { id: "ppgd-q10", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai PPGD di Mahapala Narotama?", options: ["Kepedulian, ketenangan, dan kerja sama tim dalam menyelamatkan nyawa", "Hanya soal teknik medis", "Hanya soal kecepatan tindakan", "Hanya soal perlombaan antar tim"], answer: 0 }
    ]
  },
  { id: "navigasi", title: "Navigasi Darat", badge: "Navigator", lessons: [
    { id: "navigasi-1", title: "Pengantar Navigasi Darat", content: "Navigasi darat adalah kemampuan membaca peta, kompas, dan mengenali tanda-tanda alam untuk menentukan posisi dan arah perjalanan di alam bebas. Dalam Mahapala Narotama, navigasi menjadi materi inti karena sangat penting untuk keselamatan dan keberhasilan setiap ekspedisi. Anggota dilatih untuk memahami prinsip dasar navigasi, seperti orientasi peta, penggunaan kompas, dan membaca medan. Selain itu, navigasi juga melatih ketelitian, logika, dan kerja sama tim dalam mengambil keputusan di lapangan." },
    { id: "navigasi-2", title: "Membaca Peta Topografi dan Medan", content: "Peta topografi adalah representasi permukaan bumi yang menunjukkan kontur, sungai, jalur, dan objek penting lainnya. Membaca peta membutuhkan pemahaman simbol, skala, dan interpretasi kontur untuk mengenali ketinggian dan kemiringan medan. Anggota Mahapala Narotama diajarkan cara menghubungkan peta dengan kondisi nyata di lapangan, serta teknik mengidentifikasi titik-titik orientasi seperti puncak, lembah, dan persimpangan jalur. Latihan membaca peta dilakukan secara rutin untuk meningkatkan kepercayaan diri dan akurasi navigasi." },
    { id: "navigasi-3", title: "Teknik Penggunaan Kompas dan Navigasi Alam", content: "Kompas adalah alat utama untuk menentukan arah mata angin. Teknik dasar meliputi menentukan utara magnetik, mengambil bearing, dan mengikuti azimuth. Selain kompas, tanda-tanda alam seperti posisi matahari, arah aliran sungai, dan pertumbuhan lumut juga dapat digunakan sebagai navigasi alternatif. Dalam pelatihan Mahapala Narotama, anggota diajarkan untuk selalu mengonfirmasi arah dengan lebih dari satu metode, serta mengantisipasi gangguan medan magnet atau cuaca buruk yang dapat mempengaruhi akurasi kompas." },
    { id: "navigasi-4", title: "Latihan Navigasi, Evaluasi, dan Nilai", content: "Latihan navigasi dilakukan di berbagai medan, mulai dari hutan, pegunungan, hingga rawa. Setiap latihan diakhiri dengan evaluasi: cek ketepatan rute, waktu tempuh, dan kerja sama tim. Nilai utama navigasi di Mahapala Narotama adalah ketelitian, komunikasi, dan kemampuan mengambil keputusan bersama. Pengalaman navigasi membentuk anggota yang mandiri, tangguh, dan siap menghadapi tantangan di alam bebas." }
  ], quiz: [
    { id: "navigasi-q1", question: "Jika peta menunjukkan kontur rapat dan menanjak, apa artinya?", options: ["Medan curam dan menanjak tajam", "Medan datar dan mudah dilalui", "Banyak sungai di sekitar", "Jalur tersebut pasti aman"], answer: 0 },
    { id: "navigasi-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang penggunaan kompas di lapangan?", options: ["Selalu jauhkan kompas dari benda logam dan cek bearing secara berkala", "Kompas bisa digunakan di mana saja tanpa pengaruh apapun", "Kompas hanya digunakan saat tersesat saja", "Kompas tidak perlu dikalibrasi"], answer: 0 },
    { id: "navigasi-q3", question: "Jika tersesat di hutan tanpa sinyal, apa langkah PALING TEPAT?", options: ["Tetap tenang, gunakan peta dan kompas, lalu cari tanda alam untuk orientasi", "Langsung berjalan ke arah mana saja", "Teriak terus-menerus tanpa arah", "Tunggu di tempat tanpa usaha apapun"], answer: 0 },
    { id: "navigasi-q4", question: "Apa manfaat utama latihan navigasi secara rutin?", options: ["Meningkatkan ketelitian, kepercayaan diri, dan kerja sama tim", "Agar cepat sampai tujuan saja", "Agar bisa berjalan sendiri tanpa tim", "Agar tidak perlu membawa peta"], answer: 0 },
    { id: "navigasi-q5", question: "Jika kompas menunjukkan arah berbeda dari peta, apa yang sebaiknya dilakukan?", options: ["Cek ulang posisi, pastikan tidak ada gangguan logam, dan konfirmasi dengan tanda alam", "Langsung ikuti kompas saja", "Abaikan kompas dan gunakan insting", "Tunggu sampai kompas berubah sendiri"], answer: 0 },
    { id: "navigasi-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang membaca peta topografi?", options: ["Interpretasi kontur penting untuk mengenali ketinggian dan kemiringan medan", "Hanya lihat simbol sungai saja", "Peta hanya untuk dekorasi", "Peta tidak perlu dibawa"], answer: 0 },
    { id: "navigasi-q7", question: "Jika tim kehilangan arah di kabut tebal, apa langkah PALING TEPAT?", options: ["Gunakan kompas, tetap bersama tim, dan bergerak perlahan sambil cek orientasi", "Berjalan sendiri-sendiri agar cepat keluar", "Tunggu sampai kabut hilang tanpa usaha", "Teriak tanpa arah"], answer: 0 },
    { id: "navigasi-q8", question: "Apa risiko utama jika tidak melakukan evaluasi navigasi setelah latihan?", options: ["Kesalahan berulang dan kurangnya perbaikan kemampuan", "Tim jadi lebih kompak", "Peta jadi lebih mudah dibaca", "Kompas jadi lebih akurat"], answer: 0 },
    { id: "navigasi-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai navigasi di Mahapala Narotama?", options: ["Ketelitian, komunikasi, dan pengambilan keputusan bersama", "Hanya soal kecepatan berjalan", "Hanya soal membawa alat mahal", "Hanya soal keberuntungan"], answer: 0 },
    { id: "navigasi-q10", question: "Jika menemukan sungai di peta dan di lapangan, apa yang sebaiknya dilakukan?", options: ["Cocokkan posisi di peta dengan kondisi nyata untuk orientasi", "Abaikan sungai dan terus berjalan", "Gunakan sungai hanya untuk minum", "Tunggu di sungai sampai tim lain datang"], answer: 0 }
  ] },
  { id: "sar", title: "Search and Rescue (SAR)", badge: "SAR Rescuer", lessons: [
    { id: "sar-1", title: "Pengantar SAR", content: "Search and Rescue (SAR) adalah upaya pencarian dan penyelamatan korban kecelakaan atau hilang di alam bebas. Dalam Mahapala Narotama, SAR menjadi materi lanjutan yang menuntut kesiapsiagaan, keberanian, dan kemampuan bekerja di bawah tekanan. Anggota dilatih untuk memahami prinsip dasar SAR, seperti pencarian sistematis, evakuasi korban, dan penggunaan alat komunikasi darurat. SAR juga menanamkan nilai empati, kepedulian, dan kerja sama lintas tim." },
    { id: "sar-2", title: "Teknik Pencarian dan Evakuasi", content: "Teknik pencarian meliputi pencatatan titik terakhir korban, pembagian sektor pencarian, dan penggunaan alat bantu seperti peluit, HT, atau anjing pelacak. Evakuasi korban dilakukan dengan hati-hati, memperhatikan kondisi korban dan medan. Anggota Mahapala Narotama diajarkan teknik membawa tandu, improvisasi alat evakuasi, dan penanganan korban syok atau luka berat. Setiap operasi SAR diawali dengan briefing dan pembagian tugas yang jelas." },
    { id: "sar-3", title: "Komunikasi, Simulasi, dan Evaluasi SAR", content: "Komunikasi adalah kunci keberhasilan SAR. Setiap tim harus melaporkan posisi, temuan, dan perkembangan secara berkala. Simulasi SAR dilakukan secara rutin untuk mengasah kesiapsiagaan dan koordinasi antar tim. Setelah operasi, dilakukan evaluasi menyeluruh: cek efektivitas pencarian, kecepatan evakuasi, dan kendala di lapangan. Evaluasi bertujuan meningkatkan kemampuan dan memperkuat solidaritas antar anggota." },
    { id: "sar-4", title: "Nilai, Etika, dan Tantangan SAR", content: "SAR menanamkan nilai keberanian, empati, dan etika profesional. Setiap anggota diajarkan untuk selalu mengutamakan keselamatan diri dan tim, menghormati korban, dan menjaga kerahasiaan informasi. Tantangan utama SAR adalah medan berat, cuaca buruk, dan tekanan waktu. Pengalaman SAR membentuk anggota Mahapala Narotama menjadi pribadi yang tangguh, peduli, dan siap membantu siapa saja dalam situasi darurat." }
  ], quiz: [
    { id: "sar-q1", question: "Jika tim SAR menemukan jejak kaki baru di sekitar lokasi hilangnya korban, apa langkah PALING TEPAT?", options: ["Ikuti jejak dengan hati-hati dan laporkan ke koordinator SAR", "Abaikan jejak dan lanjutkan pencarian di sektor lain", "Tunggu di tempat sampai korban kembali", "Langsung teriak memanggil korban tanpa koordinasi"], answer: 0 },
    { id: "sar-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang evakuasi korban di medan terjal?", options: ["Gunakan tandu, jaga kestabilan korban, dan koordinasi dengan tim", "Angkat korban secepatnya tanpa alat", "Bawa korban sendiri tanpa bantuan", "Tunda evakuasi sampai cuaca membaik tanpa persiapan"], answer: 0 },
    { id: "sar-q3", question: "Jika komunikasi HT terputus saat operasi SAR, apa langkah PALING TEPAT?", options: ["Gunakan sinyal darurat atau cari posisi lebih tinggi untuk sinyal", "Tunggu saja tanpa usaha", "Tinggalkan tim dan cari sendiri", "Matikan HT dan lanjutkan pencarian"], answer: 0 },
    { id: "sar-q4", question: "Apa manfaat utama simulasi SAR secara rutin?", options: ["Meningkatkan kesiapsiagaan, koordinasi, dan kecepatan respon tim", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "sar-q5", question: "Jika korban mengalami syok berat, apa tindakan PALING BENAR?", options: ["Jaga kehangatan, baringkan korban, dan pantau kondisi vital sambil menunggu evakuasi", "Beri makan dan minum sebanyak-banyaknya", "Angkat korban berdiri agar cepat pulih", "Tinggalkan korban untuk mencari bantuan"], answer: 0 },
    { id: "sar-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang briefing sebelum operasi SAR?", options: ["Pembagian tugas, penjelasan rute, dan penekanan keselamatan tim", "Langsung berangkat tanpa briefing", "Hanya koordinator yang tahu rute", "Briefing hanya untuk tim baru"], answer: 0 },
    { id: "sar-q7", question: "Jika menemukan korban dalam kondisi tidak sadar dan luka berat, apa urutan tindakan PALING TEPAT?", options: ["Cek respons, lakukan PPGD, dan evakuasi dengan hati-hati", "Langsung angkat korban tanpa cek", "Beri minum dulu baru evakuasi", "Tunggu sampai korban sadar sendiri"], answer: 0 },
    { id: "sar-q8", question: "Apa risiko utama jika tim SAR tidak melakukan evaluasi setelah operasi?", options: ["Kesalahan berulang dan kurangnya peningkatan kemampuan", "Tim jadi lebih kompak", "Alat jadi lebih awet", "Medan jadi lebih mudah"], answer: 0 },
    { id: "sar-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai SAR di Mahapala Narotama?", options: ["Keberanian, empati, dan etika profesional dalam penyelamatan", "Hanya soal kecepatan evakuasi", "Hanya soal alat canggih", "Hanya soal jumlah korban"], answer: 0 },
    { id: "sar-q10", question: "Jika operasi SAR dilakukan di malam hari dengan cuaca buruk, apa langkah PALING TEPAT?", options: ["Tingkatkan kewaspadaan, gunakan alat penerangan, dan koordinasi ketat antar tim", "Lanjutkan pencarian tanpa alat", "Tunggu sampai pagi tanpa persiapan", "Pisah tim agar lebih cepat"], answer: 0 }
  ] },

  { id: "konservasi", title: "Konservasi Alam", badge: "Conservationist", lessons: [
    { id: "konservasi-1", title: "Pengantar Konservasi Alam", content: "Konservasi alam adalah upaya menjaga, melindungi, dan memulihkan ekosistem agar tetap lestari untuk generasi sekarang dan mendatang. Dalam Mahapala Narotama, konservasi menjadi bagian penting dari setiap kegiatan, mulai dari edukasi, aksi nyata, hingga advokasi lingkungan. Anggota diajarkan untuk memahami pentingnya keseimbangan ekosistem, peran manusia dalam menjaga alam, dan dampak kerusakan lingkungan terhadap kehidupan. Konservasi juga menanamkan rasa tanggung jawab, kepedulian, dan cinta alam pada setiap anggota." },
    { id: "konservasi-2", title: "Jenis dan Strategi Konservasi", content: "Konservasi dapat berupa perlindungan flora, fauna, air, tanah, dan udara. Strategi konservasi meliputi penanaman pohon, perlindungan satwa langka, pengelolaan sampah, dan edukasi masyarakat. Anggota Mahapala Narotama dilatih untuk merancang dan melaksanakan program konservasi yang efektif, serta melakukan monitoring dan evaluasi hasilnya. Setiap aksi konservasi harus memperhatikan aspek ekologi, sosial, dan ekonomi agar berkelanjutan." },
    { id: "konservasi-3", title: "Aksi Konservasi Mahapala Narotama", content: "Aksi konservasi yang rutin dilakukan antara lain penanaman pohon, bersih-bersih lingkungan, kampanye anti sampah plastik, dan penyuluhan ke sekolah-sekolah. Setiap aksi diawali dengan perencanaan matang, pelibatan komunitas, dan dokumentasi hasil. Anggota diajarkan untuk bekerja sama dengan berbagai pihak, seperti pemerintah, LSM, dan masyarakat lokal, agar dampak konservasi lebih luas dan berkelanjutan." },
    { id: "konservasi-4", title: "Evaluasi, Nilai, dan Tantangan Konservasi", content: "Setelah aksi konservasi, dilakukan evaluasi: cek keberhasilan, tantangan, dan peluang perbaikan. Nilai utama konservasi di Mahapala Narotama adalah kepedulian, tanggung jawab, dan kolaborasi. Tantangan utama konservasi adalah perubahan perilaku, keterbatasan sumber daya, dan tekanan ekonomi. Pengalaman konservasi membentuk anggota yang peduli, inovatif, dan siap menjadi agen perubahan lingkungan." }
  ], quiz: [
    { id: "konservasi-q1", question: "Jika menemukan sampah plastik di jalur pendakian, apa langkah PALING BENAR?", options: ["Ambil dan bawa turun untuk dibuang di tempat sampah", "Biarkan saja karena bukan sampah sendiri", "Bakar di tempat tanpa pengelolaan", "Timbun di tanah agar tidak terlihat"], answer: 0 },
    { id: "konservasi-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang penanaman pohon?", options: ["Pilih jenis pohon lokal, tanam di musim hujan, dan rawat hingga tumbuh", "Tanam pohon apa saja tanpa perawatan", "Tanam pohon di musim kemarau saja", "Tanam pohon lalu tinggalkan tanpa evaluasi"], answer: 0 },
    { id: "konservasi-q3", question: "Jika ingin melindungi satwa langka di hutan, apa strategi PALING TEPAT?", options: ["Lindungi habitatnya, edukasi masyarakat, dan cegah perburuan liar", "Tangkap dan pelihara di rumah", "Biarkan saja tanpa perlindungan", "Beri makan satwa liar secara langsung"], answer: 0 },
    { id: "konservasi-q4", question: "Apa manfaat utama evaluasi setelah aksi konservasi?", options: ["Mengetahui keberhasilan, tantangan, dan peluang perbaikan", "Agar bisa mengulang aksi yang sama", "Agar lebih banyak dokumentasi", "Agar bisa mengajak lebih banyak orang"], answer: 0 },
    { id: "konservasi-q5", question: "Jika komunitas menolak aksi konservasi, apa langkah PALING BIJAK?", options: ["Lakukan pendekatan persuasif, edukasi, dan libatkan tokoh masyarakat", "Paksakan aksi tanpa izin", "Tinggalkan komunitas dan cari lokasi lain", "Abaikan saja penolakan"], answer: 0 },
    { id: "konservasi-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai konservasi di Mahapala Narotama?", options: ["Kepedulian, tanggung jawab, dan kolaborasi lintas pihak", "Hanya soal menanam pohon", "Hanya soal bersih-bersih", "Hanya soal dokumentasi"], answer: 0 },
    { id: "konservasi-q7", question: "Jika aksi konservasi gagal mencapai target, apa langkah PALING TEPAT?", options: ["Evaluasi penyebab kegagalan dan rancang strategi baru", "Biarkan saja tanpa evaluasi", "Salahkan tim lain", "Tunda aksi berikutnya tanpa alasan"], answer: 0 },
    { id: "konservasi-q8", question: "Apa risiko utama jika tidak ada monitoring setelah aksi konservasi?", options: ["Dampak aksi tidak terukur dan sulit diperbaiki", "Aksi jadi lebih mudah", "Pohon tumbuh lebih cepat", "Sampah otomatis hilang"], answer: 0 },
    { id: "konservasi-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang tantangan konservasi?", options: ["Perubahan perilaku, keterbatasan sumber daya, dan tekanan ekonomi", "Hanya soal cuaca buruk", "Hanya soal alat kurang", "Hanya soal lokasi jauh"], answer: 0 },
    { id: "konservasi-q10", question: "Jika ingin mengajak generasi muda peduli lingkungan, apa strategi PALING EFEKTIF?", options: ["Edukasi, aksi nyata, dan libatkan mereka dalam program konservasi", "Biarkan mereka belajar sendiri", "Hanya beri materi tanpa praktik", "Tunda edukasi sampai dewasa"], answer: 0 }
  ] },

  { id: "leadership", title: "Kepemimpinan Lapangan", badge: "Field Leader", lessons: [
    { id: "leadership-1", title: "Pengantar Kepemimpinan Lapangan", content: "Kepemimpinan lapangan adalah kemampuan memimpin tim dalam situasi nyata di alam bebas, di mana tantangan, risiko, dan dinamika kelompok sangat tinggi. Dalam Mahapala Narotama, kepemimpinan bukan hanya soal memberi perintah, tetapi juga soal memberi teladan, membangun kepercayaan, dan menjaga semangat tim. Setiap anggota diajarkan untuk menjadi pemimpin yang adaptif, komunikatif, dan mampu mengambil keputusan cepat di bawah tekanan." },
    { id: "leadership-2", title: "Tipe, Peran, dan Tantangan Pemimpin", content: "Ada berbagai tipe pemimpin: demokratis, otoriter, partisipatif, dan situasional. Setiap tipe memiliki kelebihan dan tantangan tersendiri. Pemimpin lapangan harus mampu membaca situasi, menyesuaikan gaya kepemimpinan, dan membagi peran secara adil. Tantangan utama adalah mengelola konflik, menjaga motivasi tim, dan memastikan keselamatan semua anggota. Dalam Mahapala Narotama, simulasi kepemimpinan dilakukan untuk melatih kemampuan ini secara langsung." },
    { id: "leadership-3", title: "Simulasi, Evaluasi, dan Nilai Kepemimpinan", content: "Simulasi kepemimpinan dilakukan dalam setiap kegiatan, mulai dari ekspedisi, pelatihan, hingga aksi sosial. Setelah simulasi, dilakukan evaluasi: cek efektivitas komunikasi, pengambilan keputusan, dan hasil kerja tim. Nilai utama kepemimpinan di Mahapala Narotama adalah tanggung jawab, komunikasi terbuka, dan keteladanan. Pengalaman kepemimpinan membentuk anggota yang percaya diri, bijak, dan siap memimpin di berbagai situasi." },
    { id: "leadership-4", title: "Etika, Komunikasi, dan Pengembangan Diri", content: "Etika kepemimpinan meliputi kejujuran, keadilan, dan penghargaan terhadap setiap anggota. Komunikasi efektif adalah kunci membangun kepercayaan dan kerja sama. Mahapala Narotama mendorong setiap anggota untuk terus belajar, menerima masukan, dan mengembangkan potensi kepemimpinan melalui refleksi dan mentoring." }
  ], quiz: [
    { id: "leadership-q1", question: "Jika tim menghadapi konflik internal saat ekspedisi, apa langkah PALING BIJAK seorang pemimpin?", options: ["Fasilitasi diskusi terbuka dan cari solusi bersama", "Abaikan konflik agar cepat selesai", "Pilih satu pihak saja tanpa dengar yang lain", "Tunda penyelesaian sampai pulang"], answer: 0 },
    { id: "leadership-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang tipe pemimpin situasional?", options: ["Menyesuaikan gaya kepemimpinan dengan kondisi dan kebutuhan tim", "Selalu otoriter di semua situasi", "Hanya demokratis tanpa kompromi", "Tidak pernah berubah gaya memimpin"], answer: 0 },
    { id: "leadership-q3", question: "Jika anggota tim kehilangan motivasi di tengah perjalanan, apa langkah PALING EFEKTIF?", options: ["Ajak diskusi, dengarkan keluhan, dan beri semangat baru", "Biarkan saja sampai motivasi kembali sendiri", "Tegur keras di depan tim", "Tunda perjalanan tanpa alasan"], answer: 0 },
    { id: "leadership-q4", question: "Apa manfaat utama evaluasi setelah simulasi kepemimpinan?", options: ["Mengetahui kelebihan, kekurangan, dan peluang pengembangan diri", "Agar bisa mengulang simulasi yang sama", "Agar lebih banyak dokumentasi", "Agar bisa mengajak lebih banyak orang"], answer: 0 },
    { id: "leadership-q5", question: "Jika pemimpin harus mengambil keputusan cepat di situasi darurat, apa prinsip PALING BENAR?", options: ["Utamakan keselamatan tim, pertimbangkan risiko, dan komunikasikan keputusan", "Ambil keputusan sendiri tanpa diskusi", "Tunda keputusan sampai semua setuju", "Pilih opsi termudah tanpa pertimbangan"], answer: 0 },
    { id: "leadership-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang komunikasi dalam kepemimpinan?", options: ["Komunikasi terbuka membangun kepercayaan dan kerja sama tim", "Komunikasi hanya satu arah dari pemimpin", "Tidak perlu komunikasi jika sudah kenal", "Komunikasi hanya saat briefing saja"], answer: 0 },
    { id: "leadership-q7", question: "Jika pemimpin melakukan kesalahan, apa langkah PALING BIJAK?", options: ["Akui kesalahan, minta maaf, dan perbaiki bersama tim", "Sembunyikan kesalahan dari tim", "Salahkan anggota lain", "Abaikan saja karena tidak penting"], answer: 0 },
    { id: "leadership-q8", question: "Apa risiko utama jika pemimpin tidak adil dalam membagi tugas?", options: ["Menurunnya kepercayaan dan motivasi anggota", "Tugas jadi lebih cepat selesai", "Tim jadi lebih kompak", "Anggota jadi lebih mandiri"], answer: 0 },
    { id: "leadership-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika kepemimpinan?", options: ["Kejujuran, keadilan, dan penghargaan pada anggota", "Selalu keras dan tegas", "Tidak perlu mendengar masukan", "Hanya fokus pada hasil akhir"], answer: 0 },
    { id: "leadership-q10", question: "Jika ingin mengembangkan potensi kepemimpinan, apa strategi PALING EFEKTIF?", options: ["Belajar dari pengalaman, refleksi, dan mentoring", "Hanya ikut pelatihan formal", "Tunggu sampai jadi pemimpin dulu", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "logistik", title: "Manajemen Logistik Lapangan", badge: "Logistics Master", lessons: [
    { id: "logistik-1", title: "Pengantar Manajemen Logistik", content: "Manajemen logistik adalah proses perencanaan, pengadaan, distribusi, dan evaluasi perlengkapan serta perbekalan selama kegiatan di alam bebas. Dalam Mahapala Narotama, logistik menjadi fondasi utama kelancaran dan keselamatan setiap ekspedisi. Anggota diajarkan untuk membuat daftar perlengkapan, menghitung kebutuhan makanan dan air, serta mengantisipasi kebutuhan darurat. Logistik juga melatih kemampuan analisis, kerja sama, dan tanggung jawab dalam tim." },
    { id: "logistik-2", title: "Perencanaan, Pengadaan, dan Distribusi Logistik", content: "Perencanaan logistik meliputi identifikasi kebutuhan, estimasi jumlah, dan penjadwalan pengadaan. Pengadaan dilakukan dengan memperhatikan kualitas, kuantitas, dan efisiensi biaya. Distribusi logistik harus adil, merata, dan sesuai peran anggota. Dalam Mahapala Narotama, setiap anggota dilibatkan dalam proses distribusi agar semua memahami pentingnya logistik dan siap bertanggung jawab atas perlengkapan masing-masing." },
    { id: "logistik-3", title: "Pengelolaan, Penghematan, dan Solusi Logistik", content: "Pengelolaan logistik mencakup penyimpanan, pemeliharaan, dan penghematan sumber daya selama kegiatan. Anggota diajarkan untuk menghindari pemborosan, memanfaatkan perlengkapan secara optimal, dan mencari solusi jika terjadi kekurangan. Simulasi logistik dilakukan untuk melatih respons cepat dan improvisasi dalam situasi darurat, seperti kehilangan perlengkapan atau keterlambatan distribusi." },
    { id: "logistik-4", title: "Evaluasi, Nilai, dan Pengembangan Logistik", content: "Setelah kegiatan, dilakukan evaluasi logistik: cek kelengkapan, kerusakan, dan sisa perbekalan. Evaluasi bertujuan memperbaiki perencanaan ke depan dan meningkatkan efisiensi. Nilai utama logistik di Mahapala Narotama adalah tanggung jawab, kerja sama, dan inovasi. Pengalaman logistik membentuk anggota yang teliti, mandiri, dan siap menghadapi tantangan di alam bebas." }
  ], quiz: [
    { id: "logistik-q1", question: "Jika tim kekurangan air minum di tengah perjalanan, apa langkah PALING BIJAK?", options: ["Evaluasi kebutuhan, hemat air, dan cari sumber air terdekat bersama tim", "Bagi air hanya untuk pemimpin saja", "Tunda minum sampai malam", "Abaikan kebutuhan anggota lain"], answer: 0 },
    { id: "logistik-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang distribusi logistik?", options: ["Distribusi adil, merata, dan sesuai peran anggota", "Distribusi hanya untuk anggota senior", "Distribusi tanpa perencanaan", "Distribusi dilakukan setelah kegiatan selesai"], answer: 0 },
    { id: "logistik-q3", question: "Jika terjadi kehilangan perlengkapan di lapangan, apa langkah PALING TEPAT?", options: ["Cari solusi bersama, improvisasi, dan evaluasi penyebab kehilangan", "Salahkan anggota yang kehilangan", "Abaikan saja karena tidak penting", "Tunda kegiatan sampai perlengkapan ditemukan"], answer: 0 },
    { id: "logistik-q4", question: "Apa manfaat utama evaluasi logistik setelah kegiatan?", options: ["Memperbaiki perencanaan dan meningkatkan efisiensi ke depan", "Agar bisa mengulang kegiatan yang sama", "Agar lebih banyak dokumentasi", "Agar bisa mengajak lebih banyak orang"], answer: 0 },
    { id: "logistik-q5", question: "Jika terjadi kelebihan makanan di akhir kegiatan, apa langkah PALING BIJAK?", options: ["Bagi sisa makanan secara adil dan bawa pulang sisa yang bisa disimpan", "Buang semua sisa makanan di hutan", "Bakar sisa makanan di lokasi", "Tinggalkan makanan untuk hewan liar"], answer: 0 },
    { id: "logistik-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang penghematan logistik?", options: ["Gunakan perlengkapan dan perbekalan secara optimal tanpa pemborosan", "Gunakan sebanyak-banyaknya agar tidak sisa", "Hanya pemimpin yang boleh menghemat", "Penghematan tidak penting dalam logistik"], answer: 0 },
    { id: "logistik-q7", question: "Jika terjadi keterlambatan distribusi logistik, apa langkah PALING EFEKTIF?", options: ["Koordinasi ulang, cek kebutuhan prioritas, dan distribusi bertahap", "Tunda kegiatan tanpa alasan", "Bagi logistik secara acak", "Abaikan kebutuhan anggota"], answer: 0 },
    { id: "logistik-q8", question: "Apa risiko utama jika logistik tidak dievaluasi setelah kegiatan?", options: ["Kesalahan berulang dan pemborosan sumber daya", "Logistik jadi lebih banyak", "Anggota jadi lebih kompak", "Perlengkapan jadi lebih awet"], answer: 0 },
    { id: "logistik-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai logistik di Mahapala Narotama?", options: ["Tanggung jawab, kerja sama, dan inovasi dalam pengelolaan sumber daya", "Hanya soal membawa barang banyak", "Hanya soal membagi makanan", "Hanya soal alat mahal"], answer: 0 },
    { id: "logistik-q10", question: "Jika ingin meningkatkan kemampuan logistik, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, evaluasi, dan belajar dari pengalaman", "Hanya ikut pelatihan formal", "Tunggu sampai jadi koordinator logistik", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "komunikasi", title: "Komunikasi Lapangan", badge: "Communicator", lessons: [
    { id: "komunikasi-1", title: "Pengantar Komunikasi Lapangan", content: "Komunikasi lapangan adalah proses pertukaran informasi, instruksi, dan koordinasi antar anggota tim selama kegiatan di alam bebas. Dalam Mahapala Narotama, komunikasi menjadi kunci utama kelancaran, keselamatan, dan efektivitas setiap kegiatan. Anggota diajarkan untuk berkomunikasi secara jelas, singkat, dan sopan, baik secara lisan, tulisan, maupun menggunakan alat bantu komunikasi." },
    { id: "komunikasi-2", title: "Alat, Kode, dan Sandi Komunikasi", content: "Alat komunikasi lapangan meliputi HT (Handy Talky), peluit, sinyal darurat, dan kode sandi. Setiap alat memiliki fungsi dan cara penggunaan yang berbeda. Kode dan sandi digunakan untuk komunikasi rahasia, efisien, dan menghindari miskomunikasi di situasi darurat. Anggota Mahapala Narotama dilatih untuk memahami dan menggunakan semua alat serta kode komunikasi dengan benar." },
    { id: "komunikasi-3", title: "Simulasi, Evaluasi, dan Nilai Komunikasi", content: "Simulasi komunikasi dilakukan dalam setiap pelatihan, mulai dari briefing, koordinasi di lapangan, hingga penanganan situasi darurat. Setelah simulasi, dilakukan evaluasi: cek kejelasan pesan, kecepatan respon, dan efektivitas koordinasi. Nilai utama komunikasi di Mahapala Narotama adalah keterbukaan, kejelasan, dan saling menghargai. Pengalaman komunikasi membentuk anggota yang percaya diri, responsif, dan siap menghadapi tantangan di alam bebas." },
    { id: "komunikasi-4", title: "Tantangan, Etika, dan Pengembangan Komunikasi", content: "Tantangan utama komunikasi lapangan adalah gangguan sinyal, perbedaan persepsi, dan tekanan situasi. Etika komunikasi meliputi kejujuran, kesabaran, dan penghargaan terhadap pendapat orang lain. Mahapala Narotama mendorong setiap anggota untuk terus mengembangkan kemampuan komunikasi melalui latihan, refleksi, dan belajar dari pengalaman." }
  ], quiz: [
    { id: "komunikasi-q1", question: "Jika HT tidak berfungsi di tengah hutan, apa langkah PALING TEPAT?", options: ["Gunakan peluit, sinyal darurat, atau cari posisi lebih tinggi untuk sinyal", "Tunggu saja tanpa usaha", "Tinggalkan tim dan cari sendiri", "Matikan HT dan lanjutkan perjalanan"], answer: 0 },
    { id: "komunikasi-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang penggunaan kode sandi?", options: ["Digunakan untuk komunikasi rahasia dan efisien di situasi darurat", "Hanya untuk gaya-gayaan", "Tidak perlu dipelajari", "Digunakan hanya saat briefing"], answer: 0 },
    { id: "komunikasi-q3", question: "Jika terjadi miskomunikasi saat koordinasi tim, apa langkah PALING EFEKTIF?", options: ["Klarifikasi pesan, diskusi terbuka, dan pastikan semua paham", "Abaikan saja karena tidak penting", "Tunda klarifikasi sampai pulang", "Salahkan anggota lain"], answer: 0 },
    { id: "komunikasi-q4", question: "Apa manfaat utama simulasi komunikasi secara rutin?", options: ["Meningkatkan kejelasan pesan, kecepatan respon, dan efektivitas koordinasi", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "komunikasi-q5", question: "Jika anggota tim tidak memahami instruksi, apa langkah PALING BIJAK?", options: ["Ulangi instruksi dengan jelas dan pastikan dipahami semua anggota", "Biarkan saja sampai paham sendiri", "Tegur keras di depan tim", "Tunda instruksi sampai kegiatan selesai"], answer: 0 },
    { id: "komunikasi-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika komunikasi?", options: ["Kejujuran, kesabaran, dan penghargaan pada pendapat orang lain", "Selalu keras dan tegas", "Tidak perlu mendengar masukan", "Hanya fokus pada hasil akhir"], answer: 0 },
    { id: "komunikasi-q7", question: "Jika terjadi gangguan sinyal saat koordinasi, apa langkah PALING EFEKTIF?", options: ["Cari posisi lebih tinggi, gunakan alat alternatif, dan tetap koordinasi", "Tunda koordinasi sampai sinyal kembali", "Abaikan saja karena tidak penting", "Pisah tim agar lebih cepat"], answer: 0 },
    { id: "komunikasi-q8", question: "Apa risiko utama jika komunikasi tidak dievaluasi setelah kegiatan?", options: ["Kesalahan berulang dan kurangnya peningkatan kemampuan", "Komunikasi jadi lebih lancar", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "komunikasi-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai komunikasi di Mahapala Narotama?", options: ["Keterbukaan, kejelasan, dan saling menghargai dalam tim", "Hanya soal alat canggih", "Hanya soal kecepatan bicara", "Hanya soal jumlah anggota"], answer: 0 },
    { id: "komunikasi-q10", question: "Jika ingin meningkatkan kemampuan komunikasi, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, refleksi, dan belajar dari pengalaman", "Hanya ikut pelatihan formal", "Tunggu sampai jadi koordinator", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "air", title: "Manajemen Air di Alam", badge: "Water Master", lessons: [
    { id: "air-1", title: "Pengantar Manajemen Air", content: "Air adalah kebutuhan utama di alam bebas. Mahapala Narotama melatih anggota untuk mengelola air dengan bijak." },
    { id: "air-2", title: "Sumber Air Alam", content: "Sumber air di alam bisa berupa sungai, mata air, dan embun." },
    { id: "air-3", title: "Teknik Penyaringan Air", content: "Penyaringan air penting untuk memastikan air layak konsumsi." },
    { id: "air-4", title: "Hemat Air di Lapangan", content: "Hemat air adalah prinsip utama dalam setiap kegiatan Mahapala Narotama." }
  ], quiz: [
    { id: "air-q1", question: "Apa tujuan utama manajemen air?", options: ["Memenuhi kebutuhan di alam", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "air-q2", question: "Apa saja sumber air di alam?", options: ["Sungai, mata air, embun", "Hanya sungai", "Hanya mata air", "Hanya embun"], answer: 0 },
    { id: "air-q3", question: "Apa manfaat penyaringan air?", options: ["Memastikan air layak konsumsi", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "air-q4", question: "Apa manfaat hemat air?", options: ["Menghindari kehabisan air", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "air-q5", question: "Apa yang harus dihindari dalam manajemen air?", options: ["Membuang air sembarangan", "Menghemat air", "Menyaring air", "Menggunakan air"], answer: 0 },
    { id: "air-q6", question: "Apa yang harus dilakukan jika air habis?", options: ["Cari sumber air baru", "Panik", "Tunggu saja", "Membuang perlengkapan"], answer: 0 },
    { id: "air-q7", question: "Apa manfaat hemat air bagi tim?", options: ["Menjamin kebutuhan terpenuhi", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "air-q8", question: "Apa yang harus dilakukan sebelum kegiatan?", options: ["Perencanaan kebutuhan air", "Langsung berangkat", "Membawa makanan saja", "Tidak membawa air"], answer: 0 },
    { id: "air-q9", question: "Apa manfaat manajemen air bagi Mahapala Narotama?", options: ["Menjamin kelancaran dan keselamatan kegiatan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "air-q10", question: "Apa yang harus dilakukan jika menemukan air keruh?", options: ["Saring dan rebus air", "Minum langsung", "Buang saja", "Buat api"], answer: 0 }
  ] },

  { id: "api", title: "Teknik Membuat Api", badge: "Fire Maker", lessons: [
    { id: "api-1", title: "Pengantar Membuat Api", content: "Api sangat penting untuk bertahan hidup di alam. Mahapala Narotama melatih teknik membuat api yang aman dan efisien." },
    { id: "api-2", title: "Bahan Bakar Alami", content: "Bahan bakar alami seperti kayu kering, daun, dan ranting digunakan untuk membuat api." },
    { id: "api-3", title: "Teknik Penyulutan Api", content: "Teknik penyulutan api meliputi penggunaan korek, batu, dan gesekan kayu." },
    { id: "api-4", title: "Keamanan Membuat Api", content: "Keamanan adalah prioritas utama saat membuat api di alam bebas." }
  ], quiz: [
    { id: "api-q1", question: "Apa tujuan utama membuat api?", options: ["Memasak dan menghangatkan diri", "Membuat bivak", "Mendaki gunung", "Membuat logistik"], answer: 0 },
    { id: "api-q2", question: "Apa saja bahan bakar alami?", options: ["Kayu kering, daun, ranting", "Batu", "Air", "Pasir"], answer: 0 },
    { id: "api-q3", question: "Apa teknik penyulutan api?", options: ["Korek, batu, gesekan kayu", "Melempar batu", "Menggali tanah", "Membakar daun"], answer: 0 },
    { id: "api-q4", question: "Apa manfaat api di alam?", options: ["Memasak, menghangatkan, penerangan", "Membuat bivak", "Mendaki gunung", "Membuat logistik"], answer: 0 },
    { id: "api-q5", question: "Apa yang harus dihindari saat membuat api?", options: ["Membakar hutan", "Menggunakan kayu kering", "Menggunakan korek", "Menggunakan batu"], answer: 0 },
    { id: "api-q6", question: "Apa manfaat keamanan saat membuat api?", options: ["Mencegah kebakaran", "Membuat bivak", "Mendaki gunung", "Membuat logistik"], answer: 0 },
    { id: "api-q7", question: "Apa yang harus dilakukan setelah membuat api?", options: ["Pastikan api padam total", "Tinggalkan saja", "Bakar semua", "Buat bivak"], answer: 0 },
    { id: "api-q8", question: "Apa manfaat api bagi tim?", options: ["Menghangatkan dan memasak", "Membuat bivak", "Mendaki gunung", "Membuat logistik"], answer: 0 },
    { id: "api-q9", question: "Apa yang harus dilakukan jika api membesar?", options: ["Padamkan segera", "Biarkan saja", "Tambahkan kayu", "Buat bivak"], answer: 0 },
    { id: "api-q10", question: "Apa manfaat membuat api bagi Mahapala Narotama?", options: ["Meningkatkan kemampuan survival", "Membuat bivak", "Mendaki gunung", "Membuat logistik"], answer: 0 }
  ] },

  { id: "flora", title: "Pengenalan Flora Alam", badge: "Flora Explorer", lessons: [
    { id: "flora-1", title: "Pengantar Flora", content: "Flora adalah tumbuhan yang hidup di alam. Mahapala Narotama mengenalkan berbagai jenis flora lokal kepada anggota." },
    { id: "flora-2", title: "Jenis-jenis Flora", content: "Jenis flora meliputi pohon, semak, dan tumbuhan bawah." },
    { id: "flora-3", title: "Manfaat Flora", content: "Flora bermanfaat sebagai sumber makanan, obat, dan perlindungan di alam." },
    { id: "flora-4", title: "Konservasi Flora", content: "Konservasi flora penting untuk menjaga keseimbangan ekosistem." }
  ], quiz: [
    { id: "flora-q1", question: "Apa tujuan utama mengenal flora?", options: ["Mengetahui manfaat dan jenis tumbuhan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "flora-q2", question: "Apa saja jenis flora?", options: ["Pohon, semak, tumbuhan bawah", "Hanya pohon", "Hanya semak", "Hanya tumbuhan bawah"], answer: 0 },
    { id: "flora-q3", question: "Apa manfaat flora?", options: ["Sumber makanan, obat, perlindungan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "flora-q4", question: "Apa manfaat konservasi flora?", options: ["Menjaga keseimbangan ekosistem", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "flora-q5", question: "Apa yang harus dihindari saat mengenal flora?", options: ["Merusak tumbuhan", "Mengamati flora", "Mencatat jenis", "Mengambil foto"], answer: 0 },
    { id: "flora-q6", question: "Apa manfaat flora bagi tim?", options: ["Sumber makanan dan obat", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "flora-q7", question: "Apa yang harus dilakukan jika menemukan flora langka?", options: ["Lindungi dan catat", "Ambil semua", "Bakar", "Buat bivak"], answer: 0 },
    { id: "flora-q8", question: "Apa manfaat flora bagi Mahapala Narotama?", options: ["Menambah pengetahuan dan kepedulian", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "flora-q9", question: "Apa yang harus dilakukan setelah mengenal flora?", options: ["Evaluasi dan edukasi", "Langsung pulang", "Bakar tumbuhan", "Buat api"], answer: 0 },
    { id: "flora-q10", question: "Apa manfaat konservasi flora bagi generasi mendatang?", options: ["Menjaga warisan alam", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 }
  ] },

  { id: "fauna", title: "Pengenalan Fauna Alam", badge: "Fauna Explorer", lessons: [
    { id: "fauna-1", title: "Pengantar Fauna", content: "Fauna adalah hewan yang hidup di alam. Mahapala Narotama mengenalkan berbagai jenis fauna lokal kepada anggota." },
    { id: "fauna-2", title: "Jenis-jenis Fauna", content: "Jenis fauna meliputi mamalia, burung, reptil, dan serangga." },
    { id: "fauna-3", title: "Manfaat Fauna", content: "Fauna bermanfaat sebagai indikator ekosistem dan sumber pengetahuan." },
    { id: "fauna-4", title: "Konservasi Fauna", content: "Konservasi fauna penting untuk menjaga keseimbangan ekosistem." }
  ], quiz: [
    { id: "fauna-q1", question: "Apa tujuan utama mengenal fauna?", options: ["Mengetahui manfaat dan jenis hewan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "fauna-q2", question: "Apa saja jenis fauna?", options: ["Mamalia, burung, reptil, serangga", "Hanya mamalia", "Hanya burung", "Hanya reptil"], answer: 0 },
    { id: "fauna-q3", question: "Apa manfaat fauna?", options: ["Indikator ekosistem, sumber pengetahuan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "fauna-q4", question: "Apa manfaat konservasi fauna?", options: ["Menjaga keseimbangan ekosistem", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "fauna-q5", question: "Apa yang harus dihindari saat mengenal fauna?", options: ["Mengganggu atau merusak habitat", "Mengamati fauna", "Mencatat jenis", "Mengambil foto"], answer: 0 },
    { id: "fauna-q6", question: "Apa manfaat fauna bagi tim?", options: ["Sumber pengetahuan dan indikator ekosistem", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "fauna-q7", question: "Apa yang harus dilakukan jika menemukan fauna langka?", options: ["Lindungi dan catat", "Ambil semua", "Bakar", "Buat bivak"], answer: 0 },
    { id: "fauna-q8", question: "Apa manfaat fauna bagi Mahapala Narotama?", options: ["Menambah pengetahuan dan kepedulian", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "fauna-q9", question: "Apa yang harus dilakukan setelah mengenal fauna?", options: ["Evaluasi dan edukasi", "Langsung pulang", "Bakar hewan", "Buat api"], answer: 0 },
    { id: "fauna-q10", question: "Apa manfaat konservasi fauna bagi generasi mendatang?", options: ["Menjaga warisan alam", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 }
  ] },

  { id: "sejarah", title: "Sejarah Mahapala Narotama", badge: "Historian", lessons: [
    { id: "sejarah-1", title: "Awal Berdiri", content: "Mahapala Narotama berdiri pada tahun 2017 sebagai UKM pecinta alam di Universitas Narotama." },
    { id: "sejarah-2", title: "Perkembangan Organisasi", content: "Organisasi berkembang pesat dengan berbagai kegiatan dan prestasi." },
    { id: "sejarah-3", title: "Kegiatan Legendaris", content: "Banyak kegiatan legendaris yang menjadi tradisi Mahapala Narotama." },
    { id: "sejarah-4", title: "Nilai dan Filosofi", content: "Nilai solidaritas, kepedulian, dan cinta alam menjadi filosofi utama Mahapala Narotama." }
  ], quiz: [
    { id: "sejarah-q1", question: "Kapan Mahapala Narotama berdiri?", options: ["2017", "2010", "2015", "2019"], answer: 0 },
    { id: "sejarah-q2", question: "Apa tujuan utama Mahapala Narotama?", options: ["Pecinta alam dan pelestarian lingkungan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "sejarah-q3", question: "Apa saja kegiatan legendaris Mahapala?", options: ["Diklat, ekspedisi, konservasi", "Hanya diklat", "Hanya ekspedisi", "Hanya konservasi"], answer: 0 },
    { id: "sejarah-q4", question: "Apa nilai utama Mahapala Narotama?", options: ["Solidaritas, kepedulian, cinta alam", "Persaingan", "Individualisme", "Konsumtif"], answer: 0 },
    { id: "sejarah-q5", question: "Apa manfaat sejarah bagi anggota?", options: ["Menambah wawasan dan kebanggaan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "sejarah-q6", question: "Apa filosofi utama Mahapala Narotama?", options: ["Cinta alam dan solidaritas", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "sejarah-q7", question: "Apa yang harus dilakukan untuk menjaga tradisi?", options: ["Melestarikan kegiatan dan nilai", "Membiarkan saja", "Membuat api", "Mendaki gunung"], answer: 0 },
    { id: "sejarah-q8", question: "Apa manfaat kegiatan Mahapala Narotama?", options: ["Meningkatkan kepedulian dan solidaritas", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "sejarah-q9", question: "Apa yang harus dilakukan setelah mengikuti kegiatan?", options: ["Evaluasi dan refleksi", "Langsung pulang", "Bakar peralatan", "Buat api"], answer: 0 },
    { id: "sejarah-q10", question: "Apa manfaat sejarah bagi Mahapala Narotama?", options: ["Menjadi inspirasi dan motivasi", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 }
  ] },

  { id: "peralatan", title: "Manajemen Peralatan Lapangan", badge: "Gear Keeper", lessons: [
    { id: "peralatan-1", title: "Pengantar Peralatan", content: "Peralatan lapangan adalah perlengkapan utama dalam setiap kegiatan Mahapala Narotama." },
    { id: "peralatan-2", title: "Jenis-jenis Peralatan", content: "Peralatan meliputi tenda, sleeping bag, matras, kompor, dan alat masak." },
    { id: "peralatan-3", title: "Perawatan Peralatan", content: "Peralatan harus dirawat dan dicek sebelum dan sesudah kegiatan." },
    { id: "peralatan-4", title: "Evaluasi Peralatan", content: "Evaluasi peralatan dilakukan untuk memastikan kelayakan dan keamanan." }
  ], quiz: [
    { id: "peralatan-q1", question: "Apa tujuan utama manajemen peralatan?", options: ["Menjamin kelancaran dan keselamatan kegiatan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "peralatan-q2", question: "Apa saja jenis peralatan lapangan?", options: ["Tenda, sleeping bag, matras, kompor", "Hanya tenda", "Hanya sleeping bag", "Hanya matras"], answer: 0 },
    { id: "peralatan-q3", question: "Apa manfaat perawatan peralatan?", options: ["Menjamin kelayakan dan keamanan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "peralatan-q4", question: "Apa manfaat evaluasi peralatan?", options: ["Perbaikan ke depan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "peralatan-q5", question: "Apa yang harus dihindari dalam manajemen peralatan?", options: ["Kerusakan dan kehilangan", "Membawa peralatan", "Merawat peralatan", "Mengecek peralatan"], answer: 0 },
    { id: "peralatan-q6", question: "Apa yang harus dilakukan sebelum kegiatan?", options: ["Cek dan siapkan peralatan", "Langsung berangkat", "Membawa makanan saja", "Tidak membawa alat"], answer: 0 },
    { id: "peralatan-q7", question: "Apa manfaat peralatan bagi tim?", options: ["Menjamin kebutuhan terpenuhi", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "peralatan-q8", question: "Apa yang harus dilakukan jika peralatan rusak?", options: ["Perbaiki atau ganti", "Panik", "Tunggu saja", "Membuang alat"], answer: 0 },
    { id: "peralatan-q9", question: "Apa manfaat evaluasi peralatan?", options: ["Perbaikan ke depan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "peralatan-q10", question: "Apa manfaat manajemen peralatan bagi Mahapala Narotama?", options: ["Menjamin kelancaran dan keselamatan kegiatan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 }
  ] },

  { id: "ekspedisi", title: "Manajemen Ekspedisi", badge: "Expeditioner", lessons: [
    { id: "ekspedisi-1", title: "Pengantar Ekspedisi", content: "Ekspedisi adalah perjalanan panjang yang membutuhkan perencanaan matang. Mahapala Narotama rutin mengadakan ekspedisi ilmiah dan petualangan." },
    { id: "ekspedisi-2", title: "Perencanaan Ekspedisi", content: "Perencanaan ekspedisi meliputi rute, logistik, dan tim." },
    { id: "ekspedisi-3", title: "Pelaksanaan Ekspedisi", content: "Pelaksanaan ekspedisi membutuhkan kerja sama dan disiplin tinggi." },
    { id: "ekspedisi-4", title: "Evaluasi Ekspedisi", content: "Evaluasi ekspedisi dilakukan untuk perbaikan dan dokumentasi pengalaman." }
  ], quiz: [
    { id: "ekspedisi-q1", question: "Apa tujuan utama ekspedisi?", options: ["Menambah pengalaman dan pengetahuan", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "ekspedisi-q2", question: "Apa saja yang harus direncanakan dalam ekspedisi?", options: ["Rute, logistik, tim", "Hanya rute", "Hanya logistik", "Hanya tim"], answer: 0 },
    { id: "ekspedisi-q3", question: "Apa manfaat pelaksanaan ekspedisi?", options: ["Kerja sama dan disiplin", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "ekspedisi-q4", question: "Apa manfaat evaluasi ekspedisi?", options: ["Perbaikan dan dokumentasi", "Membuat bivak", "Mendaki gunung", "Membuat api"], answer: 0 },
    { id: "ekspedisi-q5", question: "Apa yang harus dihindari dalam ekspedisi?", options: ["Kurang persiapan dan kerja sama", "Membawa perlengkapan", "Merawat peralatan", "Mengecek peralatan"], answer: 0 },
    { id: "ekspedisi-q6", question: "Apa yang harus dilakukan sebelum ekspedisi?", options: ["Perencanaan matang", "Langsung berangkat", "Membawa makanan saja", "Tidak membawa alat"], answer: 0 },
    { id: "ekspedisi-q7", question: "Apa manfaat ekspedisi bagi tim?", options: ["Menambah pengalaman dan pengetahuan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "ekspedisi-q8", question: "Apa yang harus dilakukan jika terjadi masalah di ekspedisi?", options: ["Cari solusi bersama", "Panik", "Tunggu saja", "Membuang perlengkapan"], answer: 0 },
    { id: "ekspedisi-q9", question: "Apa manfaat evaluasi ekspedisi?", options: ["Perbaikan ke depan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 },
    { id: "ekspedisi-q10", question: "Apa manfaat ekspedisi bagi Mahapala Narotama?", options: ["Menambah pengalaman dan pengetahuan", "Membuat api", "Membuat bivak", "Mendaki gunung"], answer: 0 }
  ] },

  { id: "survival", title: "Teknik Survival Dasar", badge: "Survivor", lessons: [
    { id: "survival-1", title: "Pengantar Survival Dasar", content: "Survival dasar adalah kemampuan bertahan hidup di alam bebas dengan memanfaatkan sumber daya yang ada dan menjaga kondisi fisik serta mental. Dalam Mahapala Narotama, survival bukan sekadar teori, tetapi latihan nyata menghadapi situasi darurat, keterbatasan logistik, dan tekanan lingkungan. Setiap anggota diajarkan untuk tetap tenang, berpikir jernih, dan mengambil keputusan cepat demi keselamatan diri dan tim." },
    { id: "survival-2", title: "Kebutuhan, Prioritas, dan Risiko Survival", content: "Kebutuhan dasar survival meliputi air, makanan, perlindungan, dan pertolongan. Prioritas utama adalah mencari air bersih, membangun perlindungan dari cuaca, dan mengelola energi. Risiko utama dalam survival adalah dehidrasi, hipotermia, dan cedera. Mahapala Narotama melatih anggota untuk mengenali tanda bahaya, mengelola risiko, dan membuat prioritas tindakan yang tepat." },
    { id: "survival-3", title: "Teknik, Improvisasi, dan Simulasi Survival", content: "Teknik survival meliputi mencari dan memurnikan air, membuat api dengan berbagai metode, membangun bivak dari bahan alami, serta mencari makanan darurat. Improvisasi sangat penting: gunakan alat seadanya, manfaatkan lingkungan, dan tetap kreatif dalam menghadapi keterbatasan. Simulasi survival dilakukan secara rutin untuk melatih respons cepat dan kesiapsiagaan anggota Mahapala Narotama." },
    { id: "survival-4", title: "Mental, Etika, dan Pengembangan Survival", content: "Mental survival adalah kemampuan mengendalikan emosi, menjaga semangat, dan tidak panik dalam situasi sulit. Etika survival meliputi menjaga kelestarian alam, tidak merusak lingkungan, dan saling membantu antar anggota. Mahapala Narotama mendorong pengembangan kemampuan survival melalui latihan, refleksi, dan berbagi pengalaman antar anggota." }
  ], quiz: [
    { id: "survival-q1", question: "Jika kehabisan air di tengah hutan, apa langkah PALING BIJAK?", options: ["Cari sumber air terdekat, gunakan teknik pemurnian, dan hemat konsumsi air", "Tunda minum sampai malam", "Bagi air hanya untuk pemimpin", "Abaikan kebutuhan air anggota lain"], answer: 0 },
    { id: "survival-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang prioritas survival?", options: ["Air bersih, perlindungan, makanan, pertolongan", "Makanan, air, perlindungan, pertolongan", "Perlindungan, makanan, air, pertolongan", "Pertolongan, makanan, air, perlindungan"], answer: 0 },
    { id: "survival-q3", question: "Jika terjadi hipotermia pada anggota, apa langkah PALING TEPAT?", options: ["Hangatkan tubuh, ganti pakaian basah, dan beri minuman hangat jika sadar", "Biarkan saja sampai hangat sendiri", "Tunda penanganan sampai pagi", "Bungkus dengan plastik saja"], answer: 0 },
    { id: "survival-q4", question: "Apa manfaat utama simulasi survival secara rutin?", options: ["Meningkatkan kesiapsiagaan, respons cepat, dan kemampuan improvisasi", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "survival-q5", question: "Jika tidak ada alat untuk membuat api, apa strategi PALING EFEKTIF?", options: ["Gunakan teknik alami seperti gesek kayu atau batu, dan manfaatkan lingkungan sekitar", "Tunda membuat api sampai pulang", "Minta api ke tim lain", "Bakar perlengkapan saja"], answer: 0 },
    { id: "survival-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika survival?", options: ["Jaga kelestarian alam, tidak merusak lingkungan, dan saling membantu", "Ambil semua yang ada di alam", "Buang sampah sembarangan", "Fokus hanya pada diri sendiri"], answer: 0 },
    { id: "survival-q7", question: "Jika anggota panik dalam situasi survival, apa langkah PALING BIJAK?", options: ["Tenangkan, beri motivasi, dan ajak berpikir jernih", "Biarkan saja sampai tenang sendiri", "Tegur keras di depan tim", "Pisahkan dari tim"], answer: 0 },
    { id: "survival-q8", question: "Apa risiko utama jika survival tidak dilatih secara rutin?", options: ["Kurang kesiapsiagaan dan respons lambat saat darurat", "Survival jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "survival-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai survival di Mahapala Narotama?", options: ["Kesiapsiagaan, kreativitas, dan kerja sama dalam menghadapi tantangan", "Hanya soal bertahan hidup sendiri", "Hanya soal alat mahal", "Hanya soal makanan enak"], answer: 0 },
    { id: "survival-q10", question: "Jika ingin meningkatkan kemampuan survival, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, refleksi, dan berbagi pengalaman", "Hanya ikut pelatihan formal", "Tunggu sampai jadi senior", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "observasi", title: "Teknik Observasi Alam", badge: "Nature Observer", lessons: [
    { id: "observasi-1", title: "Pengantar Observasi Alam", content: "Observasi alam adalah keterampilan mengamati lingkungan sekitar secara sistematis dan teliti. Dalam Mahapala Narotama, observasi bukan sekadar melihat, tetapi juga memahami interaksi antara flora, fauna, dan fenomena alam. Setiap anggota dilatih untuk mencatat detail, mengenali pola, dan mengembangkan rasa ingin tahu yang tinggi terhadap alam." },
    { id: "observasi-2", title: "Teknik, Alat, dan Proses Observasi", content: "Teknik observasi meliputi pencatatan sistematis, pengamatan visual, penggunaan alat sederhana seperti lup, teropong, dan kamera. Proses observasi dimulai dari perencanaan, pelaksanaan, hingga dokumentasi hasil. Mahapala Narotama menekankan pentingnya objektivitas, ketelitian, dan etika dalam melakukan observasi di alam bebas." },
    { id: "observasi-3", title: "Manfaat, Simulasi, dan Evaluasi Observasi", content: "Observasi bermanfaat untuk penelitian, edukasi, dan konservasi. Simulasi observasi dilakukan secara rutin untuk melatih kepekaan, ketelitian, dan kemampuan analisis anggota. Setelah observasi, dilakukan evaluasi: cek kelengkapan data, keakuratan identifikasi, dan manfaat hasil observasi bagi tim dan lingkungan." },
    { id: "observasi-4", title: "Nilai, Etika, dan Pengembangan Observasi", content: "Nilai utama observasi di Mahapala Narotama adalah kepekaan, ketelitian, dan kepedulian terhadap alam. Etika observasi meliputi tidak mengganggu flora dan fauna, menjaga kelestarian lingkungan, dan berbagi pengetahuan. Pengembangan kemampuan observasi dilakukan melalui latihan, refleksi, dan diskusi antar anggota." }
  ], quiz: [
    { id: "observasi-q1", question: "Jika menemukan spesies langka saat observasi, apa langkah PALING BIJAK?", options: ["Catat detail, dokumentasikan tanpa mengganggu, dan laporkan ke tim", "Ambil spesimen untuk koleksi pribadi", "Abaikan saja karena tidak penting", "Buat suara keras di sekitar lokasi"], answer: 0 },
    { id: "observasi-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang teknik observasi?", options: ["Pencatatan sistematis, pengamatan visual, dan penggunaan alat sederhana", "Hanya pencatatan saja", "Hanya pengamatan visual saja", "Hanya alat canggih saja"], answer: 0 },
    { id: "observasi-q3", question: "Jika terjadi perbedaan hasil identifikasi antar anggota, apa langkah PALING EFEKTIF?", options: ["Diskusi terbuka, cek referensi, dan verifikasi bersama", "Abaikan saja karena tidak penting", "Tunda klarifikasi sampai pulang", "Pilih hasil identifikasi senior saja"], answer: 0 },
    { id: "observasi-q4", question: "Apa manfaat utama simulasi observasi secara rutin?", options: ["Meningkatkan kepekaan, ketelitian, dan kemampuan analisis", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "observasi-q5", question: "Jika anggota mengganggu flora/fauna saat observasi, apa risiko PALING BESAR?", options: ["Kerusakan ekosistem dan hilangnya data akurat", "Observasi jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "observasi-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika observasi?", options: ["Tidak mengganggu flora/fauna dan menjaga kelestarian lingkungan", "Ambil semua yang ada di alam", "Buang sampah sembarangan", "Fokus hanya pada hasil foto"], answer: 0 },
    { id: "observasi-q7", question: "Jika data observasi kurang lengkap, apa langkah PALING EFEKTIF?", options: ["Lakukan observasi ulang atau lengkapi data dengan diskusi tim", "Abaikan saja karena tidak penting", "Tunda sampai ada waktu luang", "Pilih data yang ada saja"], answer: 0 },
    { id: "observasi-q8", question: "Apa risiko utama jika observasi tidak dievaluasi setelah kegiatan?", options: ["Kurang akuratnya data dan hilangnya peluang pembelajaran", "Observasi jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "observasi-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai observasi di Mahapala Narotama?", options: ["Kepekaan, ketelitian, dan kepedulian terhadap alam", "Hanya soal alat mahal", "Hanya soal foto bagus", "Hanya soal jumlah data"], answer: 0 },
    { id: "observasi-q10", question: "Jika ingin meningkatkan kemampuan observasi, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, refleksi, dan diskusi antar anggota", "Hanya ikut pelatihan formal", "Tunggu sampai jadi senior", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "kerjasama", title: "Kerja Sama Tim", badge: "Team Player", lessons: [
    { id: "kerjasama-1", title: "Pengantar Kerja Sama Tim", content: "Kerja sama tim adalah fondasi utama keberhasilan setiap kegiatan di Mahapala Narotama. Kerja sama bukan hanya soal membagi tugas, tetapi juga membangun kepercayaan, komunikasi, dan saling mendukung dalam menghadapi tantangan. Setiap anggota diajarkan untuk menghargai peran, mendengarkan pendapat, dan berkontribusi aktif demi tujuan bersama." },
    { id: "kerjasama-2", title: "Manfaat, Teknik, dan Simulasi Kerja Sama", content: "Manfaat kerja sama meliputi percepatan pekerjaan, penguatan solidaritas, dan peningkatan efektivitas tim. Teknik kerja sama meliputi pembagian tugas, koordinasi, dan komunikasi terbuka. Simulasi kerja sama dilakukan secara rutin untuk melatih respons cepat, adaptasi, dan penyelesaian masalah bersama." },
    { id: "kerjasama-3", title: "Nilai, Etika, dan Evaluasi Kerja Sama", content: "Nilai utama kerja sama di Mahapala Narotama adalah solidaritas, komunikasi, dan tanggung jawab. Etika kerja sama meliputi kejujuran, saling menghargai, dan mengutamakan kepentingan tim. Setelah kegiatan, dilakukan evaluasi: cek efektivitas kerja sama, penyelesaian konflik, dan peluang pengembangan tim." },
    { id: "kerjasama-4", title: "Tantangan, Konflik, dan Pengembangan Kerja Sama", content: "Tantangan utama kerja sama adalah perbedaan pendapat, egoisme, dan miskomunikasi. Mahapala Narotama melatih anggota untuk menyelesaikan konflik secara bijak, menjaga komunikasi, dan terus mengembangkan kemampuan kerja sama melalui latihan, refleksi, dan mentoring." }
  ], quiz: [
    { id: "kerjasama-q1", question: "Jika terjadi konflik pendapat dalam tim, apa langkah PALING BIJAK?", options: ["Diskusi terbuka, dengarkan semua pihak, dan cari solusi bersama", "Abaikan konflik agar cepat selesai", "Pilih satu pihak saja tanpa dengar yang lain", "Tunda penyelesaian sampai pulang"], answer: 0 },
    { id: "kerjasama-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang teknik kerja sama?", options: ["Pembagian tugas, koordinasi, dan komunikasi terbuka", "Hanya pembagian tugas saja", "Hanya koordinasi saja", "Hanya komunikasi saja"], answer: 0 },
    { id: "kerjasama-q3", question: "Jika anggota tidak aktif berkontribusi, apa langkah PALING EFEKTIF?", options: ["Ajak diskusi, motivasi, dan beri peran sesuai kemampuan", "Biarkan saja sampai aktif sendiri", "Tegur keras di depan tim", "Tunda peran sampai kegiatan selesai"], answer: 0 },
    { id: "kerjasama-q4", question: "Apa manfaat utama simulasi kerja sama secara rutin?", options: ["Meningkatkan respons cepat, adaptasi, dan efektivitas tim", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "kerjasama-q5", question: "Jika terjadi miskomunikasi dalam tim, apa risiko PALING BESAR?", options: ["Terganggunya kerja sama dan pencapaian tujuan", "Kerja sama jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "kerjasama-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika kerja sama?", options: ["Kejujuran, saling menghargai, dan utamakan kepentingan tim", "Ambil semua peran sendiri", "Buang sampah sembarangan", "Fokus hanya pada hasil akhir"], answer: 0 },
    { id: "kerjasama-q7", question: "Jika kerja sama tidak dievaluasi setelah kegiatan, apa risiko PALING BESAR?", options: ["Kesalahan berulang dan kurangnya pengembangan tim", "Kerja sama jadi lebih lancar", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "kerjasama-q8", question: "Apa risiko utama jika anggota egois dalam tim?", options: ["Terganggunya solidaritas dan efektivitas kerja sama", "Kerja sama jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "kerjasama-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai kerja sama di Mahapala Narotama?", options: ["Solidaritas, komunikasi, dan tanggung jawab dalam tim", "Hanya soal alat mahal", "Hanya soal pembagian tugas", "Hanya soal jumlah anggota"], answer: 0 },
    { id: "kerjasama-q10", question: "Jika ingin meningkatkan kemampuan kerja sama, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, refleksi, dan mentoring", "Hanya ikut pelatihan formal", "Tunggu sampai jadi senior", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "kebersihan", title: "Kebersihan Lingkungan Alam", badge: "Clean Keeper", lessons: [
    { id: "kebersihan-1", title: "Pengantar Kebersihan Lingkungan", content: "Kebersihan lingkungan adalah tanggung jawab utama setiap anggota Mahapala Narotama. Menjaga kebersihan bukan hanya soal membuang sampah pada tempatnya, tetapi juga menjaga kelestarian alam, kesehatan tim, dan citra organisasi. Setiap anggota diajarkan untuk peduli, teliti, dan konsisten dalam menjaga kebersihan di setiap kegiatan." },
    { id: "kebersihan-2", title: "Aksi, Teknik, dan Simulasi Kebersihan", content: "Aksi kebersihan dilakukan sebelum, selama, dan setelah kegiatan. Teknik kebersihan meliputi pengelolaan sampah, pemilahan, dan penggunaan alat kebersihan yang tepat. Simulasi kebersihan dilakukan secara rutin untuk melatih kedisiplinan, tanggung jawab, dan kepedulian anggota terhadap lingkungan." },
    { id: "kebersihan-3", title: "Manfaat, Evaluasi, dan Nilai Kebersihan", content: "Manfaat kebersihan meliputi kesehatan, kenyamanan, dan kelestarian alam. Setelah aksi kebersihan, dilakukan evaluasi: cek kebersihan lokasi, efektivitas pengelolaan sampah, dan dampak aksi terhadap lingkungan. Nilai utama kebersihan di Mahapala Narotama adalah disiplin, tanggung jawab, dan cinta alam." },
    { id: "kebersihan-4", title: "Tantangan, Etika, dan Pengembangan Kebersihan", content: "Tantangan utama kebersihan adalah kurangnya kesadaran, fasilitas terbatas, dan kebiasaan buruk. Etika kebersihan meliputi tidak membuang sampah sembarangan, mengajak orang lain peduli, dan memberi contoh baik. Pengembangan kebersihan dilakukan melalui edukasi, refleksi, dan aksi nyata di setiap kegiatan." }
  ], quiz: [
    { id: "kebersihan-q1", question: "Jika menemukan sampah di jalur pendakian, apa langkah PALING BIJAK?", options: ["Ambil dan buang pada tempatnya, ajak tim peduli", "Biarkan saja karena bukan sampah sendiri", "Bakar sampah di lokasi", "Tunda sampai turun gunung"], answer: 0 },
    { id: "kebersihan-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang teknik kebersihan?", options: ["Pengelolaan sampah, pemilahan, dan penggunaan alat yang tepat", "Hanya buang sampah saja", "Hanya pemilahan saja", "Hanya alat canggih saja"], answer: 0 },
    { id: "kebersihan-q3", question: "Jika anggota tidak peduli kebersihan, apa langkah PALING EFEKTIF?", options: ["Ajak diskusi, beri contoh, dan motivasi untuk peduli", "Biarkan saja sampai sadar sendiri", "Tegur keras di depan tim", "Tunda edukasi sampai pulang"], answer: 0 },
    { id: "kebersihan-q4", question: "Apa manfaat utama evaluasi kebersihan setelah kegiatan?", options: ["Mengetahui efektivitas aksi dan peluang perbaikan", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu aksi lain"], answer: 0 },
    { id: "kebersihan-q5", question: "Jika terjadi kekurangan fasilitas kebersihan, apa strategi PALING EFEKTIF?", options: ["Improvisasi alat, koordinasi tim, dan tetap jaga kebersihan", "Tunda aksi kebersihan", "Abaikan saja karena tidak penting", "Pisah tim agar lebih cepat"], answer: 0 },
    { id: "kebersihan-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika kebersihan?", options: ["Tidak membuang sampah sembarangan dan memberi contoh baik", "Ambil semua sampah untuk koleksi", "Buang sampah di sungai", "Fokus hanya pada sampah sendiri"], answer: 0 },
    { id: "kebersihan-q7", question: "Jika aksi kebersihan tidak dievaluasi setelah kegiatan, apa risiko PALING BESAR?", options: ["Kurang efektifnya aksi dan berulangnya kesalahan", "Aksi jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "kebersihan-q8", question: "Apa risiko utama jika anggota tidak disiplin dalam kebersihan?", options: ["Terganggunya kesehatan, kenyamanan, dan citra organisasi", "Kebersihan jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "kebersihan-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai kebersihan di Mahapala Narotama?", options: ["Disiplin, tanggung jawab, dan cinta alam", "Hanya soal alat mahal", "Hanya soal buang sampah", "Hanya soal jumlah anggota"], answer: 0 },
    { id: "kebersihan-q10", question: "Jika ingin meningkatkan kepedulian kebersihan, apa strategi PALING EFEKTIF?", options: ["Edukasi, refleksi, dan aksi nyata di setiap kegiatan", "Hanya ikut pelatihan formal", "Tunggu sampai jadi senior", "Tidak perlu belajar lagi"], answer: 0 }
  ] },

  { id: "pendakian", title: "Teknik Pendakian Gunung", badge: "Mountain Climber", lessons: [
    { id: "pendakian-1", title: "Pengantar Teknik Pendakian Gunung", content: "Pendakian gunung adalah kegiatan utama Mahapala Narotama yang menuntut persiapan matang, teknik yang benar, dan mental yang kuat. Setiap anggota diajarkan untuk memahami medan, cuaca, dan risiko yang mungkin dihadapi. Pendakian bukan hanya soal mencapai puncak, tetapi juga menjaga keselamatan, kerja sama, dan menghargai alam." },
    { id: "pendakian-2", title: "Persiapan, Peralatan, dan Simulasi Pendakian", content: "Persiapan pendakian meliputi fisik, mental, perlengkapan, dan logistik. Peralatan utama: sepatu gunung, carrier, alat navigasi, dan perlengkapan keselamatan. Simulasi pendakian dilakukan secara rutin untuk melatih teknik, manajemen waktu, dan respons terhadap situasi darurat." },
    { id: "pendakian-3", title: "Teknik, Evaluasi, dan Nilai Pendakian", content: "Teknik mendaki meliputi langkah yang efisien, ritme yang stabil, dan pengelolaan tenaga. Setelah pendakian, dilakukan evaluasi: cek efektivitas teknik, penggunaan alat, dan kerja sama tim. Nilai utama pendakian di Mahapala Narotama adalah disiplin, tanggung jawab, dan keberanian menghadapi tantangan alam." },
    { id: "pendakian-4", title: "Tantangan, Etika, dan Pengembangan Pendakian", content: "Tantangan utama pendakian adalah cuaca buruk, cedera, dan tersesat. Etika pendakian meliputi menjaga kelestarian alam, tidak merusak jalur, dan saling membantu antar pendaki. Pengembangan kemampuan pendakian dilakukan melalui latihan, refleksi, dan berbagi pengalaman antar anggota." }
  ], quiz: [
    { id: "pendakian-q1", question: "Jika cuaca tiba-tiba memburuk saat pendakian, apa langkah PALING BIJAK?", options: ["Cari perlindungan, evaluasi rute, dan koordinasi dengan tim", "Lanjutkan pendakian tanpa persiapan", "Pisah dari tim untuk mencari jalan sendiri", "Abaikan cuaca dan tetap berjalan"], answer: 0 },
    { id: "pendakian-q2", question: "Dari pilihan berikut, mana yang PALING BENAR tentang persiapan pendakian?", options: ["Fisik, mental, perlengkapan, dan logistik", "Hanya fisik saja", "Hanya perlengkapan saja", "Hanya logistik saja"], answer: 0 },
    { id: "pendakian-q3", question: "Jika anggota mengalami cedera ringan di tengah pendakian, apa langkah PALING TEPAT?", options: ["Lakukan pertolongan pertama, evaluasi kondisi, dan putuskan lanjut atau turun bersama tim", "Biarkan saja sampai sembuh sendiri", "Tunda penanganan sampai puncak", "Pisahkan anggota dari tim"], answer: 0 },
    { id: "pendakian-q4", question: "Apa manfaat utama evaluasi pendakian setelah kegiatan?", options: ["Mengetahui efektivitas teknik dan peluang perbaikan", "Agar lebih sering berkumpul saja", "Agar bisa menggunakan alat baru", "Agar tidak perlu latihan lain"], answer: 0 },
    { id: "pendakian-q5", question: "Jika terjadi kekurangan logistik di tengah perjalanan, apa strategi PALING EFEKTIF?", options: ["Evaluasi kebutuhan, hemat logistik, dan cari solusi bersama tim", "Tunda makan sampai malam", "Bagi logistik hanya untuk pemimpin", "Abaikan kebutuhan anggota lain"], answer: 0 },
    { id: "pendakian-q6", question: "Dari pilihan berikut, mana yang PALING BENAR tentang etika pendakian?", options: ["Jaga kelestarian alam, tidak merusak jalur, dan saling membantu", "Ambil semua yang ada di alam", "Buang sampah sembarangan", "Fokus hanya pada puncak"], answer: 0 },
    { id: "pendakian-q7", question: "Jika pendakian tidak dievaluasi setelah kegiatan, apa risiko PALING BESAR?", options: ["Kurang efektifnya teknik dan berulangnya kesalahan", "Pendakian jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "pendakian-q8", question: "Apa risiko utama jika anggota tidak disiplin dalam pendakian?", options: ["Terganggunya keselamatan, kenyamanan, dan keberhasilan tim", "Pendakian jadi lebih mudah", "Anggota jadi lebih kompak", "Alat jadi lebih awet"], answer: 0 },
    { id: "pendakian-q9", question: "Dari pilihan berikut, mana yang PALING BENAR tentang nilai pendakian di Mahapala Narotama?", options: ["Disiplin, tanggung jawab, dan keberanian menghadapi tantangan alam", "Hanya soal alat mahal", "Hanya soal mencapai puncak", "Hanya soal jumlah anggota"], answer: 0 },
    { id: "pendakian-q10", question: "Jika ingin meningkatkan kemampuan pendakian, apa strategi PALING EFEKTIF?", options: ["Latihan simulasi, refleksi, dan berbagi pengalaman", "Hanya ikut pelatihan formal", "Tunggu sampai jadi senior", "Tidak perlu belajar lagi"], answer: 0 }
  ] }
];
